### PR TITLE
Alternative Github

### PR DESCRIPTION
**Pull request by Galiwyx**
Hey,
Is it possible to add an alternative github logo ? Better render in the dark mode.

### CODE REVIEW

**Comment by tijme** [comment]
Thanks again for your contribution. Unfortunately I can't merge this request right now because of two things;

1. The SVG icon is actually a PNG image (it contains `data:image/png;base64.....`) and is therefore not a vector that can be scaled without losing quality.
2. The SVG icon is not in the right directory. It should be in the `github` directory (https://github.com/tijme/raivo-issuer-icons/tree/master/vectors/github). You can add as many alternative icons as you want in the GitHub directory (there are already two at this moment).

Would you mind updating the pull-request?

Thanks!

**Comment by tijme** [comment]
Maybe one of these suits your needs?

* https://cdn.freebiesupply.com/logos/large/2x/github-octocat-logo-svg-vector.svg
* https://visualpharm.com/assets/720/Github-595b40b65ba036ed117d442f.svg
* https://github.githubassets.com/images/modules/site/icons/github-one.svg

**Comment by Galiwyx** [comment]
I'm sorry, I'me a relative beginner ! The first one or second is perfect :)

**Comment by tijme** [comment]
No problem. I just refreshed the repository on the 'CDN'. It should be working now. Thanks for contributing.

I do think the new SVG's are a little bit small compared to the other icons. We can increase the size in the future if you want to.

**Pull request merged**
